
# This file was *autogenerated* from the file aj.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4)
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface

prec = _sage_const_100 

A = AffineSpace(QQ, _sage_const_2 , names=('x', 'y',)); (x, y,) = A._first_ngens(2)
C = Curve([x**_sage_const_3 *y**_sage_const_4  - x**_sage_const_2  - x*y**_sage_const_4  - _sage_const_1 ], A)

S = RiemannSurface(C.defining_polynomial(), prec = prec)
print S

