
# This file was *autogenerated* from the file by_day.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_20 = Integer(20); _sage_const_4 = Integer(4)
from sage.schemes.riemann_surfaces.riemann_surface import RiemannSurface
A = AffineSpace(QQ, _sage_const_2 , names=('x', 'y',)); (x, y,) = A._first_ngens(2)
C = Curve([x**_sage_const_2  - x*y**_sage_const_4  - x - y**_sage_const_4 ], A)
S = RiemannSurface(C.defining_polynomial(), prec = _sage_const_20 )


